trigger:
  branches:
    include:
    - personal/yankhuan/converter-vsc-extension
    - main
  tags:
    include:
    - v*

- stages: FHIR Converter Build
  jobs:
  - job: FHIR Converter Build
    displayName: FHIR Converter Build -

    strategy:
      matrix:
        Windows:
          imageName: 'windows-lastest'
        Macos:
          imageName: "macos-latest"
      maxParallel: 2

    pool:
      vmImage: $(imageName)

    variables:
      basicPath: $(Build.SourcesDirectory)/FHIR-Converter

    steps:
    - template: ./fhir-converter-pipeline.yml
